### PR TITLE
Allow percentage as a valid unit for height

### PR DESCRIPTION
**Pull request by luckylooke**
percentage is also valid css unit for height

### CODE REVIEW

**Comment by radiolips** [comment]
This seems like it would cause problems in some places. No? I know that height in percentage is really funky across different browsers.

**Comment by luckylooke** [comment]
Maybe, but should be let on user to decide, not all percentage cases are so funky ;) We are using flex and we did not catch any problems with percentage heights yet. :)

**Comment by adumesny** [comment]
actually % height makes perfect sense for nested grids where as fixed pixel doesn't!
I mean if I have a parent cell (which user can resize at will) then children probably have to take entire height and be % based. I doubt the code would allow you to add/remove row based on drag gesture though...

**Comment by adumesny** [comment]
using #1093 as I wasn't able to merge it for some reason...

**Pull request closed without merging**
