### PR TITLE
collision: more edge case fixes

### LINKED ISSUE #1094: drag heuristics can make it hard to place items (ex: web demo)
Is there a way to alter behavior when one widget is dragged on top of other?  In the demo below I am trying to insert widget "7" between "9" and "2". If I drag it directly into the gap - it assumes I want insert "7" above "2" and pushes "2" down even thought I drag "7" thru the lower portion of "2". Only if I drag "7" all the way around and over "9" directly - it moves "9" down.

Is it possible to keep the widget that is being dragged over in place to a certain point (say when widget being dragged is at over 50% of its height) ?

### PR DESCRIPTION
**Pull request by adumesny**
### Description
fix #1094

* found I needed to take entire row (not just new location) when doing collision to correctly push down bottom items first so they keep their order and prevent large objects from leapfrogging smaller ones.
(like old code used to do)
* removed _beforeDrag and _packY fields and re-use existing _orig position data which simplifies things
* removed yOffset during _fixCollisions() as it was incorrect (reverse sorting should take care of that)
* on _leave() of external item, we now restore all items to original position using restoreInitial() (prevents any error from sticking)

NEEDLESS to say, this is MUCH more complicated than the old _fixCollision() that moved to new loc then pushed anything down in that row and below (bottom first) which is dead simple... but required you to move 90% past the item when moving down.

### Checklist
- [X] Created tests which fail without the change (if possible)
- [X] All tests passing (`yarn test`)
- [X] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by Prid13** [comment]
Thank you soo much for you hard work! I really, truly appreciate it and wish more people could donate to reward your continued effort. I'm just really glad you took the time to do this :)

**Comment by adumesny** [comment]
@Prid13 thank you for the comment. Would be great if you would follow on that donation. I've been thinking of making this commercial version as it take a huge amount of time and very few do contribute.

**Comment by Prid13** [comment]
I've already donated a while back but will try donating a bit more (won't be as much, unfortunately) :) I'm thinking of using this in a commercial product myself and will be sure to donate more if I ever manage to turn a profit on it :)

**Comment by adumesny** [comment]
sorry, couldn't connect to name. Zain Mushtaq ?

**Comment by Prid13** [comment]
Yes :) but could you please delete that? Trying not to mix my online and personal identity haha 😅

**Pull request merged**
