### PR TITLE
added "gsresize" trigger

### PR DESCRIPTION
**Pull request by miroslav-peterka**
### Description
I added event "gsresize" for each "grid-stack-item" fired immediately once widget is resized. I will use it to choose specific knockout template for content according item height.

### CODE REVIEW

**Comment by radiolips** [comment]
@miroslav-peterka Thanks! What's the difference between this and the existing `resize` or `resizestart` events?

**Comment by miroslav-peterka** [comment]
@radiolips 

- resizestart is fired on start resized widget
- resize is fired by resize handler (jqueryui) on move = on every pixel

my event gsresize is populled from gridstack and it is triggered only when node changes its height size propery (how many cells is node occupied = width, height)

I'm using gridstack together with knockoutjs to create dashboard with widgets. This event I need because
I want to change inner knockout template according widget height while I resizing it.

**Comment by miroslav-peterka** [comment]
Do you see any problems why this enhancement can't be merged?

**Comment by radiolips** [comment]
@miroslav-peterka Could you change it to `self.container.trigger` instead of `$(this)`? I'm getting dependencies removed soon. Also note that I've changed the destination branch to `develop`.

Otherwise, looks good! My apologies for letting this get stale.

**Comment by wikin** [comment]
but I fired this event not over container, but widget. 

here is piece of my code to make it more clear:
```javascript
ko.components.register('ko-dashboard-widget', {
  synchronous: true,
  viewModel: {
    createViewModel: function (widgetWrapModel, componentInfo) {
      var ViewModel = function (widgetWrapModel, componentInfo) {

...        
        this.model=widgetWrapModel.model;
        this.template = widgetWrapModel.template; // this is ko.pureComputed

        $(componentInfo.element).on('gsresize', function (event, node) {
          widgetWrapModel.height(node.height); // this is ko.observable
        });
...
      }
      return new ViewModel(widgetWrapModel,componentInfo);
    }
  },
  template:[
    '<div class="grid-stack-item-content widget">',
      '<div class="in">',
          '<!-- ko template:{name:template, data:model} --><!-- /ko -->',
      '</div>',
    '</div>'
  ].join('')
});
```

**Comment by miroslav-peterka** [comment]
but I fired this event not over container, but widget. 

here is piece of my code to make it more clear:
```javascript
ko.components.register('ko-dashboard-widget', {
  synchronous: true,
  viewModel: {
    createViewModel: function (widgetWrapModel, componentInfo) {
      var ViewModel = function (widgetWrapModel, componentInfo) {

...        
        this.model=widgetWrapModel.model;
        this.template = widgetWrapModel.template; // this is ko.pureComputed

        $(componentInfo.element).on('gsresize', function (event, node) {
          widgetWrapModel.height(node.height); // this is ko.observable
        });
...
      }
      return new ViewModel(widgetWrapModel,componentInfo);
    }
  },
  template:[
    '<div class="grid-stack-item-content widget">',
      '<div class="in">',
          '<!-- ko template:{name:template, data:model} --><!-- /ko -->',
      '</div>',
    '</div>'
  ].join('')
});
```

**Comment by miroslav-peterka** [comment]
but I can change to not using this, but event.target if you wish

**Comment by radiolips** [comment]
@miroslav-peterka You're right, that's my mistake! Can you make one very tiny change? We need a space after the comma (`,`) to avoid the style tests from complaining.

**Comment by miroslav-peterka** [comment]
comma added

**Pull request merged**
