### PR TITLE
Init react wrapper creation

### PR DESCRIPTION
**Pull request by damien-schneider**
### Related Issue
#2002 

### Description

This PR initiates the creation of a React wrapper for Gridstack.

I’ve been using a similar wrapper in production in one of my applications. While it functions, there are still a few bugs, such as issues when unmounting components and accessing the API (e.g., grid?.getFloat for displaying dynamic values). With this draft pull request, I aim to collaborate and build a more stable, easy-to-use React wrapper.

To aid development, I’ve set up a Vite environment for the demo, making it easier to test and update the wrapper.

I’m also unsure how to best integrate this wrapper into the main Gridstack library, similar to the Angular integration. This PR will serve as a starting point for achieving that.

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] All tests passing (`yarn test`)
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by adumesny** [comment]
hey thank you for starting this... I'll take a look over the weekend when I have more time. But yeah once we have somehting solid we can include as part of the release like the Angular wrapper.

**Comment by wallyssonnunes-hotmart** [comment]
I've tried this PR locally and works nice, features as nested grids should be implemented/exposed by the native gridstack core, right? At least i've had some trouble making they work correctly.

**Comment by wallynm** [comment]
I've tried this PR locally and works nice, features as nested grids should be implemented/exposed by the native gridstack core, right? At least i've had some trouble making they work correctly.

**Comment by adumesny** [comment]
let's get this in an iterate. haven't had time to check it in detail yet...

**Pull request merged**
