### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ronvanpol**
Adding widget to nested grid: Cannot set property 'isOutOfGrid' of undefined

### CODE REVIEW

**Comment by adumesny** [comment]
@ronvanpol thanks for trying this PR - can you redo it using the develop branch (looks like you are pulling a bunch of my old changes for some reason) and latest code ? you should refer your bug #1143 (I can edit your msg later, so no worries)

I can otherwise put in your changes manually but I wanted to give you credit for the fix. Let me know if you want to me to handle it.

**Comment by ronvanpol** [comment]
Hi Alain, I'm not bothered about the credits. So feel free to manually put in the changes. Otherwise I'll have another go at the PR.


Op 16 feb. 2020 om 18:32 heeft Alain Dumesny <notifications@github.com> het volgende geschreven:

﻿

@ronvanpol<https://github.com/ronvanpol> thanks for trying this PR - can you redo it using the develop branch (looks like you are pulling a bunch of my old changes for some reason) and latest code ? you should refer your bug #1143<https://github.com/gridstack/gridstack.js/issues/1143> (I can edit your msg later, so no worries)

I can otherwise put in your changes manually but I wanted to give you credit for the fix. Let me know if you want to me to handle it.

**Comment by adumesny** [comment]
can you do it today ? I can get 0.6.4 out later today, otherwise I can make the PR - likely needs a bunch of testing too to make sure it doesn't break anything and right fix.

**Comment by ronvanpol** [comment]
Sadly I won't be home for the next few hours. Better to manually apply the fixes.

Op 16 feb. 2020 om 18:38 heeft Alain Dumesny <notifications@github.com> het volgende geschreven:

﻿

can you do it today ? I can get 0.6.4 out later today, otherwise I can make the PR - likely needs a bunch of testing too to make sure it doesn't break anything and right fix.

**Comment by adumesny** [comment]
closing due to PR 1149

**Pull request closed without merging**
